### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by dimmyr** [unixfreak0037/officeparser#14]
I get this error when extracting macros from XLSX documents:

Traceback (most recent call last):
  File "R:\VS\MessagingAutomation\Misc\MacroProject\Prereqs\officeparser.py", line 551, in <module>
    ofdoc = CompoundBinaryFile(args[0], parser_options)
  File "R:\VS\MessagingAutomation\Misc\MacroProject\Prereqs\officeparser.py", line 152, in __init__
    self.header = Header(self.f.read(512), parser_options)
ValueError: I/O operation on closed file

**Comment by dimmyr** [comment]
My bad.  XLSX don't contain macros :)
